#pragma once

#define EXCHANGE_VER_MAJOR 2
#define EXCHANGE_VER_MINOR 0
#define EXCHANGE_VER_PATCH 0

#define EXCHANGE_VERSION (EXCHANGE_VER_MAJOR * 10000 + EXCHANGE_VER_MINOR * 100 + EXCHANGE_VER_PATCH)
